apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-05-02T00:32:49Z"
  generation: 1
  labels:
    app: w2
  name: w2
  namespace: default
  resourceVersion: "258292"
  uid: b378a9d4-0356-461d-bbb2-ae35bc450789
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: w2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: w2
    spec:
      containers:
      - image: swoo0/mynginx:1.0
        imagePullPolicy: IfNotPresent
        name: mynginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-05-02T00:32:49Z"
    lastUpdateTime: "2023-05-02T00:32:49Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-05-02T00:32:49Z"
    lastUpdateTime: "2023-05-02T00:32:49Z"
    message: ReplicaSet "w2-7f9864ffb8" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
